import './globals.css'
import { Roboto } from 'next/font/google'
export { metadata } from '@/constants';

const inter = Roboto({
  subsets: ['latin'],
  weight: '100'
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
